### PR TITLE
Set conditional for new Factory Class

### LINKED ISSUE #268: Cannot use with Inspirations or PPB
If either of these are active first, I cannot activate RC2. SEO is fine

( ! ) Fatal error: Uncaught Error: Class 'Boldgrid\Library\Library\Plugin\Factory' not found in /home/triayt06249v/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php on line 701
( ! ) Error: Class 'Boldgrid\Library\Library\Plugin\Factory' not found in /home/triayt06249v/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php on line 701

Fatal error: Uncaught Error: Class 'Boldgrid\Library\Library\Plugin\Factory' not found in /home/triay60y4yzy/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php:701 Stack trace: #0 /home/triay60y4yzy/public_html/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php(334): Boldgrid_Backup_Admin_Core->__construct() #1 /home/triay60y4yzy/public_html/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php(72): Boldgrid_Backup->define_admin_hooks() #2 /home/triay60y4yzy/public_html/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(81): Boldgrid_Backup->__construct() #3 /home/triay60y4yzy/public_html/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(142): run_boldgrid_backup() #4 /home/triay60y4yzy/public_html/wp-admin/includes/plugin.php(2255): include('/home/triay60y4...') #5 /home/triay60y4yzy/public_html/wp-admin/plugins.php(177): plugin_sandbox_scrape('boldgrid-backup...') #6 {main} thrown in /home/triay60y4yzy/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php on line 701

### PR DESCRIPTION
**Pull request by jamesros161**
This resolves #268 by ensuring the new Factory class added to the library is not loaded if it doesn't already exist.

### CODE REVIEW

**Comment by jamesros161** [comment]
In order to replicate the issue, you would need to already have Inspirations and PPB installed and activated, and then try to install and activate total upkeep. If you do, you will get the error.

**Comment by bwmarkle** [comment]
> In order to replicate the issue, you would need to already have Inspirations and PPB installed and activated, and then try to install and activate total upkeep. If you do, you will get the error.

I get a different error:

```
Warning: Invalid argument supplied for foreach() in /home/bradm/public_html/php-54/single-site-3/wp-content/plugins/boldgrid-backup/vendor/boldgrid/library/src/Library/Plugin/Plugin.php on line 141
```

image

It appears that the changes made to the library are not backwards compatible: https://github.com/BoldGrid/post-and-page-builder/blob/master/includes/class-boldgrid-editor-premium.php#L162

**Comment by jamesros161** [comment]
> 
> 
> > In order to replicate the issue, you would need to already have Inspirations and PPB installed and activated, and then try to install and activate total upkeep. If you do, you will get the error.
> 
> I get a different error:
> 
> ```
> Warning: Invalid argument supplied for foreach() in /home/bradm/public_html/php-54/single-site-3/wp-content/plugins/boldgrid-backup/vendor/boldgrid/library/src/Library/Plugin/Plugin.php on line 141
> ```
> 
> image
> 
> It appears that the changes made to the library are not backwards compatible: https://github.com/BoldGrid/post-and-page-builder/blob/master/includes/class-boldgrid-editor-premium.php#L162

This should be resolved by the library PR https://github.com/BoldGrid/library/pull/62

**Comment by bwmarkle** [comment]
@jamesros161 with your fix to the library, I am now getting the error everyone else is getting:

```
[22-May-2020 16:40:24 UTC] PHP Fatal error:  Uncaught Error: Class 'Boldgrid\Library\Library\Plugin\Factory' not found in /home/bradm/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php:701
```

... So, if the Plugin\Factory does not exist, it means that the correct library is not loading. While this fix may address the specific error, it means that there will be other parts of the code that needing and missing code from the library, and this will result in random errors where we have to add these "if class exists" checks at. So, while I may be running backup 1.14, I don't actually have all the features available to that version because there's a library issue.

The core issue that needs to be addressed in this ticket is why the Factory class is missing if it is included in the vendor folder?

**Comment by bwmarkle** [comment]
To help narrow down the issue, the testing instructions say:

> In order to replicate the issue, you would need to already have Inspirations and PPB installed and activated, and then try to install and activate total upkeep. If you do, you will get the error.

I replicated the issue with only Inspirations running. PPB may not be involved.

**Comment by bwmarkle** [comment]
@jamesros161 This is not working.

1. Ensure both **boldgrid-backup** and **boldgrid-backup/vendor/boldgrid/library** are on _issue-268_
1. Disable all BoldGrid plugins
1. Enable BoldGrid Inspirations
1. Enable Total Upkeep

I get the following error:

```
Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Call to undefined method Boldgrid\Library\Library\Plugin\Plugins::getAllPlugins() in /home/user/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-auto-updates.php on line 64

Error: Call to undefined method Boldgrid\Library\Library\Plugin\Plugins::getAllPlugins() in /home/user/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-auto-updates.php on line 64

1 | 0.0021 | 401792 | {main}( ) | .../plugins.php:0
2 | 0.8827 | 15754416 | plugin_sandbox_scrape( ) | .../plugins.php:177
3 | 0.8830 | 15755080 | include( '/home/user/public_html/wp-content/plugins/boldgrid-backup/boldgrid-backup.php' ) | .../plugin.php:2255
4 | 0.8885 | 15814880 | run_boldgrid_backup( ) | .../boldgrid-backup.php:142
5 | 0.8885 | 15814976 | Boldgrid_Backup->__construct( ) | .../boldgrid-backup.php:81
6 | 0.9497 | 16484360 | Boldgrid_Backup->define_admin_hooks( ) | .../class-boldgrid-backup.php:72
7 | 0.9539 | 16578128 | Boldgrid_Backup_Admin_Core->__construct( ) | .../class-boldgrid-backup.php:334
8 | 0.9752 | 16730272 | Boldgrid_Backup_Admin_Auto_Updates->__construct( ) | .../class-boldgrid-backup-admin-core.php:709
```

**Pull request merged**
