### PR TITLE
changed boldgrid-backup-admin-table-include.js to boldgrid-backup-adm…

### PR DESCRIPTION
**Pull request by jamesros161**
This pull request is to address [https://github.com/BoldGrid/boldgrid-backup/issues/182](https://github.com/BoldGrid/boldgrid-backup/issues/182) .

the file boldgrid-backup-admin-table-include.js was being blocked by All In One WP Security by adding the following line to the site's .htaccess file:
`RedirectMatch 403 include\.`

Changing the name from boldgrid-backup-admin-table-include.js to boldgrid-backup-admin-table-includes.js resolves this issue by no longer matching the pattern include\.

### CODE REVIEW

**Comment by aevansWL** [comment]
Hi, I'm having this exact issue using WP Security and BoldGrid backup with that setting enabled. I see the info about changing a file name and know where to find the file. Is this something I can do without breaking something in BoldGrid Backup? Is there somewhere else BoldGrid needs to be pointed to know where to find this file? Or is this something that will be included in a plugin update?

**Comment by aevansWL** [comment]
I did find something calling for this .js file in class-boldgrid-backup-admin-db-omit.php. I changed the .js file name as stated about as well as the mention of it in the above file. No more error about not including databases is present and no 404s so far. Of course, I'm sure any plugin update to come would wipe this out so I'll bookmark this page in case I start seeing the errors again.

Please comment though and let me know if I did anything problematic or need to do anything additional to the above.

**Comment by bwmarkle** [comment]
Hi @aevansWL thanks for info! Can you tell us exactly how we can replicate the issue? IE install WP Security and Total Upkeep, and then where do we go and what exact error do we see?

Thanks!

**Comment by aevansWL** [comment]
I’ll do my best. :)

To start, I was seeing a 404 from my own IP address in some logs with the WP All-in-One Security app for boldgrid-backup-admin-table-include.js.

I did some searching about it which led me here, where I saw this mentioned: “Changing the name from boldgrid-backup-admin-table-include.js to boldgrid-backup-admin-table-includes.js resolves this issue by no longer matching the pattern include.”

I changed the file name as mentioned above, then checked things by going to Total Upkeep > Backups and choosing Backup Now. Then I saw the error saying all tables would not be included (even though all were checked).

I went back into the plugin files and found that the file class-boldgrid-backup-admin-db-omit.php calls for this file. I changed the name of the ...include.js mention to ...includes.js within the ...omit.php (it shows in two places but only one needs to be changed, I don’t know coding but I think the other was the name of the label or function which should probably stay the same I assume).

I then checked for errors again by going to do a Backup, and the error was gone. Backup also was successful as far as I can tell.

Hope this helps.

**Comment by bwmarkle** [comment]
Hi @aevansWL, I just tested and I see the issue is still occurring. I think I see the problem. I'll touch base shortly.

Thanks!

**Comment by bwmarkle** [comment]
Hi @aevansWL,

We just released Total Upkeep 1.13.11 which fixes this issue.

The fix applied in February via this Pull Request was merged into the master branch, but it doesn't look like we've released master since then. If you upgrade to 1.13.11, this issue should be resolved.

Thanks!
- Brad

**Pull request merged**
