### PR TITLE
Site Check notification update

### PR DESCRIPTION
**Pull request by cssjoe**
To test:
* [x] Edit a PHP file to create a syntax error.
* [x] Run the command (in directory "wp-content/plugins/boldgrid-backup/cli/") `php bgbkup-cli.php check notify email=$USER@boldgrid.com`
* [ ] Check for an email and review the contents.  There will be a link to the GitHub Wiki page for help and a link to BoldGrid Backup Settings for the site.

### CODE REVIEW

**Comment by bwmarkle** [comment]
grammar: 

> You should check your site and can perform a manual restoration.

**Comment by bwmarkle** [comment]
I was thinking about an updated email message... Thoughts on the below?

> Hi,
> 
> This is the BoldGrid Backup plugin running at your site, DOMAIN.COM. We recently checked your site and noticed that it's not loading correctly. We detected the following error:
> 
> Uncaught Error: Call to undefined function arequire_once() in /home/user/public_html/wp-config.php:90
> Stack trace:
> #0 /home/user/public_html/wp-load.php(37): require_once()
> #1 /home/user/public_html/wp-content/plugins/boldgrid-backup/cli/wp-test.php(96): require('/home/user/pub...')
> #2 {main}
>   thrown in /home/user/public_html/wp-config.php on line 90
> 
> For more help with troubleshooting this error, as well as information on how you can restore your website if needed, please visit the following page:
> 
> What to do when BoldGrid Backup Site Check Fails - https://www.boldgrid.com/support/boldgrid-backup/what-to-do-when-boldgrid-backup-site-check-fails/
> 
> Best regards,
> - The BoldGrid Backup plugin
> 
> Email notifications from BoldGrid Backup can be managed within your BoldGrid Backup Settings page - https://domain.com/wp-admin/admin.php?page=boldgrid-backup-settings

**Comment by cssjoe** [comment]
It sounds like you want the email to resemble WordPress's Site Health email message.  I did want to keep the format standardized with the other emails that send from the plugin; same greeting, salutation, etc.  If we change the format, then we should do it for the other emails as well.

Since the user may receive two emails (one from BGB and another from WP Site Health), we may want to say something about the WP email and that WP >= 5.2 includes that feature and a recovery mode.  Possible our support article can also reference the WP recovery mode.  If a user has a WP < 5.2, then we can recommend that they upgrade.

We do have the siteurl, which is used in the current message.  Just having the domain may not be enough, since there may be other installations on the same domain.  It's nice to have the full link to the site so that the recipient can simply click to check the site in a browser.

The email is in plain text, and not in HTML, so we don't have fancy links.

For the error information, we have only what is discovered by https://www.php.net/manual/en/function.error-get-last.php and not able to perform a stack/debug backtrace at the point when the failure is turned over to the shutdown function error handler.

The rest of the proposed content looks ok.

**Comment by bwmarkle** [comment]
I've provided my feedback... Accepting PR.

**Pull request merged**
