### PR TITLE
Site Check

### LINKED ISSUE #12: Auto Recovery
My site just crashed. Have a cron that will figure this out and auto restore site.

### PR DESCRIPTION
**Pull request by cssjoe**
Fixes #12 -- Site Check and logging.

# Testing Instructors
1. [x] Perform a backup.
1. [x] Change directory to: `wp-content/plugins/boldgrid-backup/`.
1. [x] Run the command: `php cron/bgbkup-cli.php check log log_level=LOG_DEBUG`.
1. [x] Break a PHP file, such as `wp-config.php`.
1. [ ] Run the chack command again.
1. [ ] Review the log file: `bgbkup-cli.log`.

### CODE REVIEW

**Comment by bwmarkle** [comment]
When running the test, I get the following:
```
wp-content/plugins/boldgrid-backup(detection)$ php cron/bgbkup-cli.php check log log_level=LOG_DEBUG
Error: No backup information found in the log file "/home/usre/boldgrid_backup/domain-b2cf0453-20190502-120746.log".
```
Is this intended?

**Comment by bwmarkle** [comment]
Holding off on further review until more info on this pull request is received. It may help to have a GitHub wiki page discussing exactly what this feature is, how it's supposed to work, etc.

**Comment by cssjoe** [comment]
A backup log file should be created when a backup is made.  Look into why there is no log file present.

**Comment by bwmarkle** [comment]
I caused this error:

> Parse error: syntax error, unexpected 'define' (T_STRING) in /home/user/public_html/wp-config.php on line 30

But the check command still came back with:

```
boldgrid-backup(detection)$ php cron/bgbkup-cli.php check log log_level=LOG_DEBUG

Info: No action taken.
```

**Comment by cssjoe** [comment]
I can add debug_print_backtrace output when a fatal is encountered.  I can also hide the auto recover option on the settings page until we test it further.

**Comment by cssjoe** [comment]
Moved to https://github.com/BoldGrid/boldgrid-backup/pull/70

**Pull request closed without merging**
